# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ALL_PROTEINS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Protein_Key', models.IntegerField()),
                ('Key_coourence_no', models.IntegerField(default=0)),
                ('aacd0', models.CharField(max_length=5, null=True)),
                ('position0', models.CharField(max_length=5, null=True)),
                ('aacd1', models.CharField(max_length=5, null=True)),
                ('position1', models.CharField(max_length=5, null=True)),
                ('aacd2', models.CharField(max_length=5, null=True)),
                ('position2', models.CharField(max_length=5, null=True)),
                ('classT1', models.IntegerField(default=0)),
                ('Theta', models.FloatField(default=0.0)),
                ('classL1', models.IntegerField(default=0)),
                ('maxDist', models.FloatField(default=0.0)),
                ('x0', models.FloatField(default=0.0)),
                ('y0', models.FloatField(default=0.0)),
                ('z0', models.FloatField(default=0.0)),
                ('x1', models.FloatField(default=0.0)),
                ('y1', models.FloatField(default=0.0)),
                ('z1', models.FloatField(default=0.0)),
                ('x2', models.FloatField(default=0.0)),
                ('y2', models.FloatField(default=0.0)),
                ('z2', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ARCHITECTURE_DESCRIPTION',
            fields=[
                ('Architecture', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('DescriptionOfArchitecture', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CLASS_DESCRIPTION',
            fields=[
                ('Class', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('DescriptionOfClass', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='HOMOLOGYSUPERFAMILY_DESCRIPTION',
            fields=[
                ('HomologySuperfamily', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('DescriptionOfHomologySuperfamily', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='POSITION_INFORMATION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AminoAcid_Name', models.CharField(max_length=20)),
                ('Seq_ID', models.IntegerField()),
                ('X_COORD', models.FloatField(default=0.0)),
                ('Y_COORD', models.FloatField(default=0.0)),
                ('Z_COORD', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='PROTEIN_HIERARCHY',
            fields=[
                ('Protein_ID', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('Architecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.ARCHITECTURE_DESCRIPTION')),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.CLASS_DESCRIPTION')),
                ('HomologySuperfamily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.HOMOLOGYSUPERFAMILY_DESCRIPTION')),
            ],
        ),
        migrations.CreateModel(
            name='SIMILARITY_INFORMATION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Similarity_Value', models.FloatField(default=0.0)),
                ('Protein_ID1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protein_id1', to='compare.PROTEIN_HIERARCHY')),
                ('Protein_ID2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protein_id2', to='compare.PROTEIN_HIERARCHY')),
            ],
        ),
        migrations.CreateModel(
            name='TOPOLOGYFOLD_DESCRIPTION',
            fields=[
                ('TopologyFold', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('DescriptionOfTopologyFold', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='protein_hierarchy',
            name='TopologyFold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.TOPOLOGYFOLD_DESCRIPTION'),
        ),
        migrations.AddField(
            model_name='position_information',
            name='Protein_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.PROTEIN_HIERARCHY'),
        ),
        migrations.AddField(
            model_name='all_proteins',
            name='Protein_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.PROTEIN_HIERARCHY'),
        ),
    ]
