# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position_information',
            name='Seq_ID',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
