# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0002_auto_20170920_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='ALL_PROTEINStest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Protein_ID', models.CharField(max_length=20, unique=True)),
                ('Protein_Key', models.IntegerField()),
                ('Key_coourence_no', models.IntegerField(default=0)),
                ('aacd0', models.CharField(max_length=5, null=True)),
                ('position0', models.CharField(max_length=5, null=True)),
                ('aacd1', models.CharField(max_length=5, null=True)),
                ('position1', models.CharField(max_length=5, null=True)),
                ('aacd2', models.CharField(max_length=5, null=True)),
                ('position2', models.CharField(max_length=5, null=True)),
                ('classT1', models.IntegerField(default=0)),
                ('Theta', models.FloatField(default=0.0)),
                ('classL1', models.IntegerField(default=0)),
                ('maxDist', models.FloatField(default=0.0)),
                ('x0', models.FloatField(default=0.0)),
                ('y0', models.FloatField(default=0.0)),
                ('z0', models.FloatField(default=0.0)),
                ('x1', models.FloatField(default=0.0)),
                ('y1', models.FloatField(default=0.0)),
                ('z1', models.FloatField(default=0.0)),
                ('x2', models.FloatField(default=0.0)),
                ('y2', models.FloatField(default=0.0)),
                ('z2', models.FloatField(default=0.0)),
            ],
        ),
    ]
