# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0003_all_proteinstest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_proteinstest',
            name='Protein_ID',
            field=models.CharField(max_length=20),
        ),
    ]
