# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0005_auto_20171118_1328'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='all_proteins',
            index_together=set([('Protein_ID', 'Protein_Key')]),
        ),
    ]
