# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0008_auto_20171130_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_proteins',
            name='Theta',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='all_proteins',
            name='aacd0',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='all_proteins',
            name='aacd1',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='all_proteins',
            name='aacd2',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='all_proteins',
            name='classL1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='all_proteins',
            name='classT1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='all_proteins',
            name='maxDist',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='all_proteins',
            name='position0',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='all_proteins',
            name='position1',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='all_proteins',
            name='position2',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='all_proteins',
            name='x0',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='all_proteins',
            name='x1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='all_proteins',
            name='x2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='all_proteins',
            name='y0',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='all_proteins',
            name='y1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='all_proteins',
            name='y2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='all_proteins',
            name='z0',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='all_proteins',
            name='z1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='all_proteins',
            name='z2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='all_proteins_big',
            name='Theta',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='all_proteins_big',
            name='aacd0',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='all_proteins_big',
            name='aacd1',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='all_proteins_big',
            name='aacd2',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='all_proteins_big',
            name='classL1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='all_proteins_big',
            name='classT1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='all_proteins_big',
            name='maxDist',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='all_proteins_big',
            name='position0',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='all_proteins_big',
            name='position1',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='all_proteins_big',
            name='position2',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='all_proteins_big',
            name='x0',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='all_proteins_big',
            name='x1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='all_proteins_big',
            name='x2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='all_proteins_big',
            name='y0',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='all_proteins_big',
            name='y1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='all_proteins_big',
            name='y2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='all_proteins_big',
            name='z0',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='all_proteins_big',
            name='z1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='all_proteins_big',
            name='z2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='all_proteins_big_unindexed',
            name='Theta',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='all_proteins_big_unindexed',
            name='aacd0',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='all_proteins_big_unindexed',
            name='aacd1',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='all_proteins_big_unindexed',
            name='aacd2',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='all_proteins_big_unindexed',
            name='classL1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='all_proteins_big_unindexed',
            name='classT1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='all_proteins_big_unindexed',
            name='maxDist',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='all_proteins_big_unindexed',
            name='position0',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='all_proteins_big_unindexed',
            name='position1',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='all_proteins_big_unindexed',
            name='position2',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='all_proteins_big_unindexed',
            name='x0',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='all_proteins_big_unindexed',
            name='x1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='all_proteins_big_unindexed',
            name='x2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='all_proteins_big_unindexed',
            name='y0',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='all_proteins_big_unindexed',
            name='y1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='all_proteins_big_unindexed',
            name='y2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='all_proteins_big_unindexed',
            name='z0',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='all_proteins_big_unindexed',
            name='z1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='all_proteins_big_unindexed',
            name='z2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='all_proteins',
            name='Key_coourence_no',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='all_proteins_big',
            name='Key_coourence_no',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='all_proteins_big_unindexed',
            name='Key_coourence_no',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
