"""
Django settings for protein project.

Generated by 'django-admin startproject' using Django 1.10.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

ALLOWED_HOSTS = []
DEBUG = True

PROTEIN_APPS = [
    'compare',
    'search'
]
INSTALLED_APPS = DJANGO_APPS + PROTEIN_APPS

MIDDLEWARE = ['django.contrib.sessions.middleware.SessionMiddleware',
              'django.middleware.common.CommonMiddleware',
              'django.middleware.csrf.CsrfViewMiddleware',
              'django.contrib.auth.middleware.AuthenticationMiddleware',
              'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
              'django.contrib.messages.middleware.MessageMiddleware',
              'django.middleware.clickjacking.XFrameOptionsMiddleware',
              'django.middleware.security.SecurityMiddleware',
              ]

ROOT_URLCONF = 'protein.urls'
APPEND_SLASH = True

TEMPLATES = [
    {'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
     },
]

WSGI_APPLICATION = 'protein.wsgi.application'

SECRET_KEY = '0ju&3d_@t0ltpc^oxx4*prg^46029tty0^298!-_6all+2)_*-'
# Media files (CSS, JavaScript, Images)

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = '/media/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "static/")
STATIC_URL = '/static/'
STATICFILES_DIRS = (MEDIA_ROOT,)

COMPARE_DIR = os.path.join(BASE_DIR, "compare")
HIERARCHY_FILE = os.path.join(COMPARE_DIR, "hierarchy.csv")

try:
    from local_settings import *
except ImportError:
    pass
